//$file${Src::main_app.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: tetris.qm
// File:  ${Src::main_app.c}
//
// This code has been generated by QM 7.0.2 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${Src::main_app.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


#include "main_app.h"
#include <stdio.h>
#include "app_config.h"
#include "NRF_chip.h"
#include "main.h";

//DMA buffer
static __attribute__((section(".bss"))) __attribute__((aligned(4))) volatile uint32_t Sensor_dht11_dma_buffer[DHT11_MAX_EDGES];

//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 730U) || (QP_VERSION != ((QP_RELEASE^4294967295U)%0x2710U))
#error qpc version 7.3.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${AOs::MainApp} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::MainApp} ............................................................
MainApp MainApp_inst;

//${AOs::MainApp::calc_dryness_percent} ......................................
uint8_t MainApp_calc_dryness_percent(uint16_t dryness) {
    if(dryness >= MAX_DRY)
    {
        return 100;
    }

    if((uint16_t) dryness <= (uint16_t) MAX_WET)
    {
        return 0;
    }

    uint8_t percent = 0;

    percent = ((dryness - MAX_WET) * 100) / (MAX_DRY - MAX_WET);

    return percent;
}

//${AOs::MainApp::SM} ........................................................
QState MainApp_initial(MainApp * const me, void const * const par) {
    //${AOs::MainApp::SM::initial}
    return Q_TRAN(&MainApp_display);
}

//${AOs::MainApp::SM::display} ...............................................
QState MainApp_display(MainApp * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::MainApp::SM::display}
        case Q_ENTRY_SIG: {
            QTimeEvt_armX(&me->tempPollEvt,
                          800U,    // Fire after 10 seconds
                          800U);   // Then repeat every 10 seconds

            HAL_GPIO_WritePin(GPIOA, GPIO_PIN_5, GPIO_PIN_RESET);
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::MainApp::SM::display::initial}
        case Q_INIT_SIG: {
            status_ = Q_TRAN(&MainApp_display_stats);
            break;
        }
        //${AOs::MainApp::SM::display::SENSOR_DONE}
        case SENSOR_DONE_SIG: {
            SensorEvent const *sensorEvt = (SensorEvent const *)e;

            me->currentTemp = sensorEvt->temperature;

            uint16_t tempDry = sensorEvt->dryness;

            switch(me->currentState)
            {
                case TEMPERATURE:
                display_temp(me->currentTemp);
                break;

                case DRYNESS:
                    uint8_t p = MainApp_calc_dryness_percent(tempDry);
                    me->currentDryness = p;
                    display_dry(p);
                break;
                default:
                        // error
                        break;

            }

            status_ = Q_HANDLED();
            break;
        }
        //${AOs::MainApp::SM::display::POLL_SENSOR}
        case POLL_SENSOR_SIG: {
            static QEvt const ADC_Start_Evt = {START_SENSOR_SIG, 0U, 0U};
            QACTIVE_POST(AO_Sensor,&ADC_Start_Evt, me);
            verify_rx_mode();
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::MainApp::SM::display::BUTTON_PRESS}
        case BUTTON_PRESS_SIG: {
            QTimeEvt_disarm(&me->longPressEvt);
            QTimeEvt_armX(&me->longPressEvt, LONG_PRESS_TIME_MS / 10, 0U);
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::MainApp::SM::display::BUTTON_LONG}
        case BUTTON_LONG_SIG: {
            status_ = Q_TRAN(&MainApp_pump);
            break;
        }
        //${AOs::MainApp::SM::display::BUTTON_RELEASE}
        case BUTTON_RELEASE_SIG: {
            QTimeEvt_disarm(&me->longPressEvt);

            if(me->currentState == TEMPERATURE)
            {
                me->currentState = DRYNESS;
                display_dry(me->currentDryness);
            }
            else
            {
                me->currentState = TEMPERATURE;
                display_temp(me->currentTemp);
            }
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

//${AOs::MainApp::SM::display::display_stats} ................................
QState MainApp_display_stats(MainApp * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::MainApp::SM::display::display_stats}
        case Q_ENTRY_SIG: {
            display_temp(me->currentTemp);

            status_ = Q_HANDLED();
            break;
        }
        //${AOs::MainApp::SM::display::display_stats}
        case Q_EXIT_SIG: {
            QTimeEvt_disarm(&me->tempPollEvt);
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&MainApp_display);
            break;
        }
    }
    return status_;
}

//${AOs::MainApp::SM::pump} ..................................................
QState MainApp_pump(MainApp * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::MainApp::SM::pump}
        case Q_ENTRY_SIG: {
            printf("enter pump\n");
            QTimeEvt_disarm(&me->longPressEvt);
            HAL_GPIO_WritePin(GPIOA, GPIO_PIN_5, GPIO_PIN_SET);


            status_ = Q_HANDLED();
            break;
        }
        //${AOs::MainApp::SM::pump}
        case Q_EXIT_SIG: {
            printf("exit pump\n");
            HAL_GPIO_WritePin(GPIOA, GPIO_PIN_5, GPIO_PIN_RESET);
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::MainApp::SM::pump::BUTTON_RELEASE}
        case BUTTON_RELEASE_SIG: {
            printf("released the btm inside pump \n");
            status_ = Q_TRAN(&MainApp_display_stats);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
//$enddef${AOs::MainApp} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${Shared} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${Shared::AO_Main_App} .....................................................
QActive * const AO_Main_App = &MainApp_inst.super;

//${Shared::Main_App_ctor} ...................................................
void Main_App_ctor(MainApp * const me) {
    QActive_ctor(&me->super, Q_STATE_CAST(&MainApp_initial));
    QTimeEvt_ctorX(&me->tempPollEvt, &me->super, POLL_SENSOR_SIG, 0U);
    QTimeEvt_ctorX(&me->longPressEvt, &me->super, BUTTON_LONG_SIG, 0U);
    me->currentTemp = 0.0f;
}

//${Shared::AO_Sensor} .......................................................
QActive * const AO_Sensor = &Sensor_inst.super;

//${Shared::Sensor_ctor} .....................................................
void Sensor_ctor(Sensor * const me) {
    QActive_ctor(&me->super, Q_STATE_CAST(&Sensor_initial));

    me->dma_buffer = Sensor_dht11_dma_buffer;
    me->dma_index = 0;

}

//${Shared::AO_RFButton} .....................................................
QActive * const AO_RFButton = &RFButton_inst.super;

//${Shared::RFButton_ctor} ...................................................
void RFButton_ctor(RFButton * const me) {
    QActive_ctor(&me->super, Q_STATE_CAST(&RFButton_initial));

}
//$enddef${Shared} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



