//$file${Src::rfbutton.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: tetris.qm
// File:  ${Src::rfbutton.c}
//
// This code has been generated by QM 7.0.2 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${Src::rfbutton.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "rfbutton.h"
#include "main_app.h"
#include "NRF_chip.h"
//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 730U) || (QP_VERSION != ((QP_RELEASE^4294967295U)%0x2710U))
#error qpc version 7.3.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${AOs::RFButton} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::RFButton} ...........................................................
RFButton RFButton_inst;

//${AOs::RFButton::receive_rf} ...............................................
void RFButton_receive_rf(void) {
    while(nrf24_data_available()) {
            uint8_t payload[PLD_S];
            nrf24_receive(payload, sizeof(payload));
            //QACTIVE_POST(AO_Main_App, &evt->super, me);
        }
}

//${AOs::RFButton::SM} .......................................................
QState RFButton_initial(RFButton * const me, void const * const par) {
    //${AOs::RFButton::SM::initial}
    return Q_TRAN(&RFButton_wait);
}

//${AOs::RFButton::SM::wait} .................................................
QState RFButton_wait(RFButton * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::RFButton::SM::wait}
        case Q_ENTRY_SIG: {
            printf("wait\n");

            status_ = Q_HANDLED();
            break;
        }
        //${AOs::RFButton::SM::wait::NRF_IRQ}
        case NRF_IRQ_SIG: {
            RFButton_receive_rf();
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
//$enddef${AOs::RFButton} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
