//$file${Src::sensor.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: tetris.qm
// File:  ${Src::sensor.c}
//
// This code has been generated by QM 7.0.2 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${Src::sensor.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "sensor.h"
#include <stdio.h>
#include "main_app.h"
#include "app_config.h"
#include "temp_sensor.h"

extern ADC_HandleTypeDef hadc1;
//extern TIM_HandleTypeDef htim3;
//extern DMA_HandleTypeDef hdma;
//extern DMA_HandleTypeDef hdma_tim3_ch1;
//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 730U) || (QP_VERSION != ((QP_RELEASE^4294967295U)%0x2710U))
#error qpc version 7.3.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${AOs::Sensor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::Sensor} .............................................................
Sensor Sensor_inst;

//${AOs::Sensor::get_adc_dryness} ............................................
uint16_t Sensor_get_adc_dryness(void) {
    // Start ADC conversion
    HAL_ADC_Start(&hadc1);

    // Wait for conversion to complete
    if (HAL_ADC_PollForConversion(&hadc1, 10) == HAL_OK) { // timeout in ms
        // Read the converted value
        return (uint16_t)HAL_ADC_GetValue(&hadc1);
    }

    return 0;
}

//${AOs::Sensor::SM} .........................................................
QState Sensor_initial(Sensor * const me, void const * const par) {
    //${AOs::Sensor::SM::initial}
    return Q_TRAN(&Sensor_waiting);
}

//${AOs::Sensor::SM::waiting} ................................................
QState Sensor_waiting(Sensor * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::Sensor::SM::waiting}
        case Q_ENTRY_SIG: {
            printf("waiting SENSOR \n");
            QTimeEvt_disarm(&me->resetEvt);

            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Sensor::SM::waiting::START_SENSOR}
        case START_SENSOR_SIG: {
            printf("start SENSOR \n");
            for(int i=0;i<5;i++) me->bits[i]=0;
            me->bit_index = 0;
            me->byte_index = 0;
            QTimeEvt_armX(&me->resetEvt, DHT11_RESET_TIME, 0U);

            status_ = Q_TRAN(&Sensor_start_temperature);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

//${AOs::Sensor::SM::start_temperature} ......................................
QState Sensor_start_temperature(Sensor * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::Sensor::SM::start_temperatur~::initial}
        case Q_INIT_SIG: {
            printf("INIT sensor\n");
            // Pull DHT11 LOW ≥18ms
            DHT11_SetPinOutput();
            HAL_GPIO_WritePin(DHT11_PORT, DHT11_PIN, GPIO_PIN_RESET);
            Delay_ms(20);
            HAL_GPIO_WritePin(DHT11_PORT, DHT11_PIN, GPIO_PIN_SET);
            // Switch pin to input
            DHT11_SetPinInput();
            Delay_us(30);


            status_ = Q_TRAN(&Sensor_wait_response);
            break;
        }
        //${AOs::Sensor::SM::start_temperatur~::DHT11_RESET}
        case DHT11_RESET_SIG: {
            QTimeEvt_disarm(&me->resetEvt);
            printf("Reset DHT11");
            status_ = Q_TRAN(&Sensor_waiting);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

//${AOs::Sensor::SM::start_temperatur~::wait_response} .......................
QState Sensor_wait_response(Sensor * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::Sensor::SM::start_temperatur~::wait_response}
        case Q_ENTRY_SIG: {
            me->bit_index = 0;
            me->byte_index = 0;
            me->reading_high = true;
            me->pulse_count = 0;
            memset(me->bits, 0, sizeof(me->bits));
            printf("ENTRY SENSOR \n");

            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Sensor::SM::start_temperatur~::wait_response::DHT11_TIMER_IC}
        case DHT11_TIMER_IC_SIG: {
            uint32_t localTimestamps[TIMESTAMP_SIZE];
            BSP_get_timestamps(localTimestamps);

            for(uint8_t i = 0; i < TIMESTAMP_SIZE; i++)
            {
                if(i < 3) { continue; } // ignore ack, start

                if (i % 2 == 1) { // positive edge (HIGH pulse duration)
                    // Determine if the current HIGH pulse represents a '1' or '0'
                    uint8_t bit_val = (localTimestamps[i] > 40) ? 1 : 0;  // FIXED!

                    // Store bit in the main bits array
                    if (bit_val) {
                        me->bits[me->byte_index] |= (1 << (7 - me->bit_index));
                    } else {
                        me->bits[me->byte_index] &= ~(1 << (7 - me->bit_index));
                    }

                    // Move to next bit
                    me->bit_index++;

                    // If a byte is complete, move to next byte
                    if (me->bit_index > 7) {
                        me->bit_index = 0;
                        me->byte_index++;

                        // If 5 bytes (40 bits) are read, finalize
                        if (me->byte_index >= 5) {
                            // Verify checksum
                            uint8_t checksum = me->bits[0] + me->bits[1] + me->bits[2] + me->bits[3];
                            if (checksum == me->bits[4]) {
                                uint16_t dryness_val = Sensor_get_adc_dryness();

                                SensorEvent *evt = Q_NEW(SensorEvent, SENSOR_DONE_SIG);
                                evt->dryness = dryness_val;
                                evt->temperature = me->bits[2];

                                QACTIVE_POST(AO_Main_App, &evt->super, NULL);
                                status_ = Q_TRAN(&Sensor_waiting);
                                break;


                            } else {
                                printf("Checksum error! Expected: %u, Got: %u\n",
                                       checksum, me->bits[4]);
                            }

                            // Reset or go to waiting state
                            //status_ = Q_TRAN(&Sensor_waiting);
                            break;
                        }
                    }
                } // ADDED: Close the if (i % 2 == 0) block
            }




            status_ = Q_TRAN(&Sensor_waiting);
            break;
        }
        default: {
            status_ = Q_SUPER(&Sensor_start_temperature);
            break;
        }
    }
    return status_;
}
//$enddef${AOs::Sensor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



// DMA buffer must be in RAM, not flash
// Must be in RAM for DMA, do NOT use 'const'
//static __attribute__((aligned(4))) volatile uint32_t dht11_dma_buffer[DHT11_MAX_EDGES];
//static volatile uint8_t dma_index = 0;

//QActive * const AO_Sensor = &Sensor_inst;
