//$file${Src::sensor.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: tetris.qm
// File:  ${Src::sensor.c}
//
// This code has been generated by QM 7.0.2 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${Src::sensor.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "sensor.h"
#include <stdio.h>
#include "main_app.h"
#include "app_config.h"
#include "temp_sensor.h"



extern ADC_HandleTypeDef hadc1;
//extern TIM_HandleTypeDef htim3;
//extern DMA_HandleTypeDef hdma;
//extern DMA_HandleTypeDef hdma_tim3_ch1;
//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 730U) || (QP_VERSION != ((QP_RELEASE^4294967295U)%0x2710U))
#error qpc version 7.3.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${AOs::Sensor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::Sensor} .............................................................
Sensor Sensor_inst;

//${AOs::Sensor::SM} .........................................................
QState Sensor_initial(Sensor * const me, void const * const par) {
    //${AOs::Sensor::SM::initial}
    return Q_TRAN(&Sensor_waiting);
}

//${AOs::Sensor::SM::waiting} ................................................
QState Sensor_waiting(Sensor * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::Sensor::SM::waiting}
        case Q_ENTRY_SIG: {
            //__HAL_LINKDMA(&htim3, hdma[TIM_DMA_ID_CC1], hdma_tim3_ch1);

            // Start input capture with DMA
            //HAL_TIM_IC_Start_DMA(&htim3, TIM_CHANNEL_1, (uint32_t *)me->dma_buffer, DHT11_MAX_EDGES);
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Sensor::SM::waiting::START_SENSOR}
        case START_SENSOR_SIG: {

            for(int i=0;i<5;i++) me->bits[i]=0;
            me->bit_index = 0;
            me->byte_index = 0;


            status_ = Q_TRAN(&Sensor_start_temperature);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

//${AOs::Sensor::SM::start_temperature} ......................................
QState Sensor_start_temperature(Sensor * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::Sensor::SM::start_temperatur~::initial}
        case Q_INIT_SIG: {
            // Pull DHT11 LOW ≥18ms
            DHT11_SetPinOutput();
            HAL_GPIO_WritePin(DHT11_PORT, DHT11_PIN, GPIO_PIN_RESET);
            // Use HAL delay (blocking) just for start signal
            //BSP_delayMs(20);
            Delay_ms(20);
            HAL_GPIO_WritePin(DHT11_PORT, DHT11_PIN, GPIO_PIN_SET);
            // Switch pin to input
            Delay_us(30);
            DHT11_SetPinInput();
            // Start timer input capture
            //HAL_TIM_IC_Start_IT(&htim16, TIM_CHANNEL_1);

            status_ = Q_TRAN(&Sensor_wait_response);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

//${AOs::Sensor::SM::start_temperatur~::wait_response} .......................
QState Sensor_wait_response(Sensor * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::Sensor::SM::start_temperatur~::wait_response}
        case Q_ENTRY_SIG: {
            me->bit_index = 0;
            me->byte_index = 0;
            me->reading_high = false;
            me->pulse_count = 0;
            memset(me->bits, 0, sizeof(me->bits));

            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Sensor::SM::start_temperatur~::wait_response::DHT11_TIMER_IC}
        case DHT11_TIMER_IC_SIG: {
            uint32_t pulse_length = ((DHT11Evt const *)e)->pulse_length;

            me->pulse_count++;

            // Skip first 2 pulses (response: 80µs LOW + 80µs HIGH)
            if (me->pulse_count <= 2) {
                status_ = Q_HANDLED();
                break;
            }

            // Now process data bits
            me->reading_high = !me->reading_high;

            if (me->reading_high) {
                // We're measuring the HIGH pulse (data bit)
                if (pulse_length > 40) {  // threshold between 0 and 1
                    // logical 1 (70µs)
                    me->bits[me->byte_index] |= (1 << (7 - me->bit_index));
                }
                // else bit=0 by default (26-28µs)

                me->bit_index++;
                if (me->bit_index > 7) {
                    me->bit_index = 0;
                    me->byte_index++;

                    if (me->byte_index >= 5) {
                        // Done reading 40 bits
                        //HAL_TIM_IC_Stop_IT(&htim3, TIM_CHANNEL_1);

                        // Verify checksum
                        uint8_t checksum = me->bits[0] + me->bits[1] + me->bits[2] + me->bits[3];
                        if (checksum == me->bits[4]) {
                            // Valid data
                            printf("Humidity: %u.%u%%  Temperature: %u.%u°C\n",
                                   me->bits[0], me->bits[1],
                                   me->bits[2], me->bits[3]);
                        } else {
                            printf("Checksum error! Expected: %u, Got: %u\n",
                                   checksum, me->bits[4]);
                        }

                        status_ = Q_TRAN(&Sensor_waiting);
                        break;
                    }
                }
            }
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&Sensor_start_temperature);
            break;
        }
    }
    return status_;
}
//$enddef${AOs::Sensor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



// DMA buffer must be in RAM, not flash
// Must be in RAM for DMA, do NOT use 'const'
//static __attribute__((aligned(4))) volatile uint32_t dht11_dma_buffer[DHT11_MAX_EDGES];
//static volatile uint8_t dma_index = 0;

//QActive * const AO_Sensor = &Sensor_inst;
