//$file${Inc::main_app.h} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: tetris.qm
// File:  ${Inc::main_app.h}
//
// This code has been generated by QM 7.0.2 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${Inc::main_app.h} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#ifndef MAIN_APP_H
#define MAIN_APP_H

#include "qpc.h"
#include "temp_sensor.h"
#include "display.h"
#include "plant_sensor.h"
#include "sensor.h"



//keep track of substates
typedef enum {
    TEMPERATURE,
    DRYNESS
} display_states;

//$declare${AOs::MainApp} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::MainApp} ............................................................
typedef struct MainApp {
// protected:
    QActive super;

// private:

// public:
    QTimeEvt  tempPollEvt;

// private:
    uint8_t currentTemp;
    uint16_t currentDryness;
    display_states currentState;
} MainApp;

extern MainApp MainApp_inst;

// private:
uint8_t MainApp_calc_dryness_percent(uint16_t dryness);

// protected:
QState MainApp_initial(MainApp * const me, void const * const par);
QState MainApp_display(MainApp * const me, QEvt const * const e);
QState MainApp_display_stats(MainApp * const me, QEvt const * const e);
//$enddecl${AOs::MainApp} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$declare${Shared} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${Shared::AO_Main_App} .....................................................
extern QActive * const AO_Main_App;

//${Shared::Main_App_ctor} ...................................................
void Main_App_ctor(MainApp * const me);

//${Shared::AO_Sensor} .......................................................
extern QActive * const AO_Sensor;

//${Shared::Sensor_ctor} .....................................................
void Sensor_ctor(Sensor * const me);
//$enddecl${Shared} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
// Signals
enum MenuGameSignals {
    BUTTON_PRESS_SIG = Q_USER_SIG,
    POLL_SENSOR_SIG,
    BUTTON_SHORT_SIG,
    BUTTON_LONG_SIG,
    START_SENSOR_SIG,
    SENSOR_DONE_SIG,
    MAX_SIG  // Keep last for validation
};


//events

typedef struct {
    QEvt super;
    uint16_t dryness;
    uint16_t temperature;
} SensorEvent;



#endif
