//$file${Inc::main_app.h} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: tetris.qm
// File:  ${Inc::main_app.h}
//
// This code has been generated by QM 7.0.2 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${Inc::main_app.h} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#ifndef MAIN_APP_H
#define MAIN_APP_H

#include "qpc.h"
#include "temp_sensor.h"
#include "display.h"
#include "plant_sensor.h"
#include "sensor.h"
#include "rfbutton.h"
#include "tetris_board.h"
#include "tetromino.h"

//keep track of substates
typedef enum {
    TEMPERATURE,
    DRYNESS
} display_states;

//$declare${AOs::MainApp} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::MainApp} ............................................................
typedef struct MainApp {
// protected:
    QActive super;

// private:

// public:
    QTimeEvt  tempPollEvt;

// private:
    uint8_t currentTemp;
    uint16_t currentDryness;
    display_states currentState;

// public:
    QTimeEvt longPressEvt;
    QTimeEvt dryTimerEvt;

// private:
    LineState line_state_inst;
    Board board_inst;
    uint8_t line_w ;
    uint8_t line_h ;
    uint8_t line_x0 ;
    uint8_t line_y0 ;
    Tetromino active_tetromino;
} MainApp;

extern MainApp MainApp_inst;

extern uint32_t  MainApp_delta_time;

extern uint8_t MainApp_score;

// private:
uint8_t MainApp_calc_dryness_percent(uint16_t dryness);
void MainApp_init_line_state(
    LineState * ls,
    int x0,
    int y0,
    int x1,
    int y1);
void MainApp_spawn_tetromino(MainApp * const me);

// protected:
QState MainApp_initial(MainApp * const me, void const * const par);
QState MainApp_display(MainApp * const me, QEvt const * const e);
QState MainApp_display_stats(MainApp * const me, QEvt const * const e);
QState MainApp_dry_alert(MainApp * const me, QEvt const * const e);
QState MainApp_pump(MainApp * const me, QEvt const * const e);
QState MainApp_tetris(MainApp * const me, QEvt const * const e);
QState MainApp_game(MainApp * const me, QEvt const * const e);
QState MainApp_init_board(MainApp * const me, QEvt const * const e);
QState MainApp_top_border(MainApp * const me, QEvt const * const e);
QState MainApp_left_border(MainApp * const me, QEvt const * const e);
QState MainApp_btm_border(MainApp * const me, QEvt const * const e);
QState MainApp_right_border(MainApp * const me, QEvt const * const e);
QState MainApp_gameover_screen(MainApp * const me, QEvt const * const e);
QState MainApp_win_sceen(MainApp * const me, QEvt const * const e);
//$enddecl${AOs::MainApp} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$declare${Shared} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${Shared::AO_Main_App} .....................................................
extern QActive * const AO_Main_App;

//${Shared::Main_App_ctor} ...................................................
void Main_App_ctor(MainApp * const me);

//${Shared::AO_Sensor} .......................................................
extern QActive * const AO_Sensor;

//${Shared::Sensor_ctor} .....................................................
void Sensor_ctor(Sensor * const me);

//${Shared::AO_RFButton} .....................................................
extern QActive * const AO_RFButton;

//${Shared::RFButton_ctor} ...................................................
void RFButton_ctor(RFButton * const me);
//$enddecl${Shared} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
// Signals
enum MenuGameSignals {
    BUTTON_PRESS_SIG = Q_USER_SIG,
    POLL_SENSOR_SIG,
    BUTTON_SHORT_SIG,
    BUTTON_LONG_SIG,
    BUTTON_RELEASE_SIG,
    START_SENSOR_SIG,
    SENSOR_DONE_SIG,
    NRF_IRQ_SIG,
    DHT11_START_SIG,
    DHT11_TIMER_IC_SIG,
    DHT11_RESET_SIG,
    DHT11_DONE_SIG,
    PLANT_DRY_SIG,
    WATER_PLANT_SIG,
    START_TETRIS_SIG,
    GAMEOVER_TETRIS_SIG,
    WON_TETRIS_SIG,
    DRAW_OUTLINE_SIG,
    DRAW_OUTLINE_DONE_SIG,
    MAX_SIG
};


//events

typedef struct {
    QEvt super;
    uint16_t dryness;
    uint16_t temperature;
} SensorEvent;


#endif
