//$file${Inc::sensor.h} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: tetris.qm
// File:  ${Inc::sensor.h}
//
// This code has been generated by QM 7.0.2 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${Inc::sensor.h} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#ifndef SENSOR_H
#define SENSOR_H

#include "qpc.h"

//$declare${AOs::Sensor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::Sensor} .............................................................
typedef struct Sensor {
// protected:
    QActive super;

// private:

// public:
    uint8_t bits[5];
    uint8_t bit_index;
    uint8_t byte_index;

// private:
    bool reading_high;
    uint8_t pulse_count;
    volatile uint32_t* dma_buffer;
    uint8_t dma_index;
    QTimeEvt resetEvt;
    QTimeEvt dht11StartEvt;
} Sensor;

extern Sensor Sensor_inst;

// private:
uint16_t Sensor_get_adc_dryness(void);

// protected:
QState Sensor_initial(Sensor * const me, void const * const par);
QState Sensor_waiting(Sensor * const me, QEvt const * const e);
QState Sensor_wait_response(Sensor * const me, QEvt const * const e);
QState Sensor_start_dht(Sensor * const me, QEvt const * const e);
QState Sensor_turn_off(Sensor * const me, QEvt const * const e);
QState Sensor_turn_on(Sensor * const me, QEvt const * const e);
//$enddecl${AOs::Sensor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


#endif
